---
title: "Loading Datasets"
output: html_notebook
---


```{r}
dir <- "/Users/manasvikhanna/Desktop/Farmer's Protest"
setwd(dir)
```


```{r}
# #install.packages('spatstat')
# loading packages
library(dplyr)
library(tidyr)
library(ggmap)
library(spatstat)
library(tigris)
library(spdep)
library(ggplot2)
library(broom)
library(sp)
library(raster)
library(tidycensus)
library(maditr)
library(gridExtra)
```

```{r}
allProtests <- read.csv("Farmer's Protest Data.csv")
colnames(allProtests)
describe(allProtests$year)
```

```{r}
farmers_protest <- filter(allProtests,year >2018)
table(farmers_protest$year)
```
```{r}
farmers_protest = separate_rows(farmers_protest,assoc_actor_1,sep = ";")
#unique(farmers_protest$assoc_actor_1)
```

```{r}
state_shape1 <- rgdal::readOGR(dsn = "/Users/manasvikhanna/Desktop/Farmer's Protest/shape_files/India_States_ADM1_GADM-shp", layer = "3e563fd0-8ea1-43eb-8db7-3cf3e23174512020330-1-layr7d.ivha")

state_shape2 <- rgdal::readOGR(dsn = "/Users/manasvikhanna/Desktop/Farmer's Protest/shape_files/India-State-and-Country-Shapefile-Updated-Jan-2020-master", 
                               layer = "India_State_Boundary")

state_shape3 <- rgdal::readOGR(dsn = "/Users/manasvikhanna/Desktop/Farmer's Protest/shape_files/maps-f0f120311fefd5049b0dab6856c2fa5bf06e9b08/States",
                               layer= "Admin2")



district_shape <- rgdal::readOGR(dsn = "/Users/manasvikhanna/Desktop/Farmer's Protest/shape_files/data (1)", layer = "polbnda_ind")
plot(district_shape)
```
```{r}
I_map <- ggmap(get_map(c(left = 67, bottom = 8.063, right = 97.141, top = 36.7), source = "stamen"))
# farmers_plot <- farmers_protest %>% filter(assoc_actor_1 %in% c("BKU: Bharatiya Kisan Union"," AIKSCC: All India Farmers' Struggle Coordination Committee",
#                                                      "INC: Indian National Congress"," SKM: United Farmers Front", " VCK: Viduthalai Chiruthaigal Katchi")) 
# I_map+geom_point(data=farmers_plot, aes(x=longitude, y =latitude, col = assoc_actor_1))+labs(col = "Actor Name") + scale_color_brewer(palette="Accent")+ geom_point(size = 5)

```

```{r}
land_use<-read.csv("ESTIMATED AREA BY SIZE CLASSES AND LAND USE by STATE - Sheet1.csv")
tail(land_use)
# remove empty rows
land_use <- land_use %>% slice(-c(1,2))
land_use <- land_use %>% slice(-c(37)) # remove all cities total
tail(land_use)
```


```{r}
# transformations
copy_protest <- farmers_protest
coordinates(copy_protest) <- ~longitude+latitude 
class(copy_protest)
```

```{r}
proj4string(copy_protest) <- "+proj=longlat +datum=NAD83 +no_defs"
proj4string(copy_protest)
copy_protest<- spTransform(copy_protest, proj4string(state_shape3))
in_fortify <- broom::tidy(state_shape3)
state_shape3$id <- row.names(state_shape3)
in_fortify <- left_join(in_fortify, state_shape3@data)

bbox(state_shape3)
bbox(copy_protest) # bounding box! 
```

Processing predicted population dataset 
```{r}
predicted_pop <- read.csv("modified_india_population_data.xlsx - Sheet1.csv")
predicted_pop$State<- tolower(predicted_pop$State)
# subset only total popultion 
predicted_pop_total <- subset(predicted_pop, Gender=="Persons", select=State:X2021_pop)
predicted_pop_total <- predicted_pop_total[order(predicted_pop_total$State),]
head(predicted_pop_total)
```
```{r}
# modifying the database to show actual values 
predicted_pop_total$State <- gsub('[*]', '',as.character(predicted_pop_total$State))
predicted_pop_total$X2019_pop <- gsub(',', '',as.character(predicted_pop_total$X2019_pop))
predicted_pop_total$X2020_pop <- gsub(',', '',as.character(predicted_pop_total$X2020_pop))
predicted_pop_total$X2021_pop <- gsub(',', '',as.character(predicted_pop_total$X2021_pop))

head(predicted_pop_total)

predicted_pop_total$X2019_pop <- (as.integer(as.character(predicted_pop_total$X2019_pop)))*1000
predicted_pop_total$X2020_pop <- (as.integer(as.character(predicted_pop_total$X2020_pop)))*1000
predicted_pop_total$X2021_pop <- (as.integer(as.character(predicted_pop_total$X2021_pop)))*1000

head(predicted_pop_total)

```


```{r} 
# change state names to lower case to match each other
state_shape3@data$ST_NM <- tolower(state_shape3@data$ST_NM)
land_use$State.Name <- tolower(land_use$State.Name)

```


```{r} 
# change '&' to 'and' in land use db
#land_use$State.Name <- gsub('&', 'and', land_use$State.Name)

# change specific variables in land use db to match state shape db
land_use$State.Name <- gsub('a & n islands', 'andaman & nicobar island', land_use$State.Name)
predicted_pop_total$State <- gsub('andaman & nicobar islands', 'andaman & nicobar island'
                                  , predicted_pop_total$State)
predicted_pop_total$State <- gsub('dadra & nagar haveli', 'dadara & nagar havelli'
                                  , predicted_pop_total$State)
predicted_pop_total$State <- gsub('jammu & kashmir (ut)', 'jammu & kashmir',
                                  predicted_pop_total$State)
predicted_pop_total$State <- gsub('chandigarh ', 'chandigarh',
                                  predicted_pop_total$State)

land_use$State.Name <- gsub('d & n haveli', 'dadara & nagar havelli', land_use$State.Name)
land_use$State.Name <- gsub('telengana', 'telangana', land_use$State.Name)
land_use$State.Name <- gsub('chattisgarh', 'chhattisgarh', land_use$State.Name)
land_use$State.Name <- gsub('delhi', 'nct of delhi', land_use$State.Name)

# change names in state shape 
state_shape3@data$ST_NM <- gsub('arunanchal pradesh', 'arunachal pradesh', state_shape3@data$ST_NM)

```

Combined all the demographic data with the shape file
```{r}
# match land use and state shape 
state_shape3@data <- left_join(state_shape3@data, land_use, by = c("ST_NM" = "State.Name"))
state_shape3@data <- left_join(state_shape3@data, predicted_pop_total, by = c("ST_NM" = "State"))

View(state_shape3@data)
#write.csv(state_shape3@data, file = "demographic_data.csv",row.names = FALSE)
```


We want to try plotting the dataset
```{r}
# check overlap
over_ds <-over(copy_protest,state_shape3)
length(which(is.na(over_ds$ST_NM)))
```

```{r}
# check overlap
copy_protest <- copy_protest@data[over_ds$ST_NM,]
copy_protest <- copy_protest %>% as.data.frame()
nrow(copy_protest)

# agg_data <- plyr::count(over_ds, c('ST_NM'))
# colnames(agg_data) <- c("ST_NM", "num_protest")
# state_shape3@data <- left_join(state_shape3@data, agg_data, by = (ST_NM = "ST_NM"))
```

```{r}
class(state_shape3)
state_fortify <- broom::tidy(state_shape3)
state_shape3$ST_NM <- row.names(state_shape3)
state_fortify <- left_join(state_fortify, state_shape3@data)
```

```{r}
I_map + geom_polygon(data= state_fortify, aes(x = long, y = lat,
                              group = group, fill = (Total.Holdings.Number)),
                     col = "black") + scale_fill_distiller(palette = "Spectral")
              
```

